name: make-environment

description: "make environment"

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
    - name: make environment
      shell: bash
      run: make install
    - name: Install wasm-pack
      shell: bash
      run: curl --proto '=https' --tlsv1.2 -sSf https://rustwasm.github.io/wasm-pack/installer/init.sh | sh
