import { writeFile } from "node:fs/promises";
import path from "node:path";
import { ERROR_CODE_MESSAGE_MAP } from "./error_code_message_map";
import { WARNING_CODE_MESSAGE_MAP } from "./warning_code_message_map";

type DiagnosticEntry = [string, { en: string; ja: string }];

/** Converts public diagnostic spellings into Rust enum variant names. */
function toRustVariant(code: string): string {
  return code
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

/** Generates an enum from the same localized messages used by JavaScript clients. */
function makeEnum({
  name,
  derives,
  entries,
}: {
  name: string;
  derives: string;
  entries: DiagnosticEntry[];
}): string {
  const variants = entries
    .map(
      ([code, messages]) =>
        `    #[strum(serialize = "${code}")]\n` +
        `    /**\n` +
        `     * en: ${messages.en}\n` +
        `     * ja: ${messages.ja}\n` +
        `     */\n` +
        `    ${toRustVariant(code)},\n`,
    )
    .join("\n");

  return `#[derive(${derives})]\npub enum ${name} {\n${variants}}\n`;
}

/** Builds deterministic Rust sources without writing files when this module is imported. */
export function generateDiagnosticSources(): {
  errorCode: string;
  warningCode: string;
} {
  const header =
    "// NOTE: Do not edit this file manually, it is generated by generate_diagnostic_codes.ts\n";
  const errorEnum = makeEnum({
    name: "ErrorCode",
    derives: "Debug, Clone, Copy, PartialEq, Eq, Display, EnumString",
    entries: Object.values(ERROR_CODE_MESSAGE_MAP).flatMap((group) =>
      Object.entries(group),
    ),
  });
  const warningEnum = makeEnum({
    name: "WarningCode",
    derives: "Debug, Clone, Copy, PartialEq, Eq, Display",
    entries: Object.entries(WARNING_CODE_MESSAGE_MAP),
  });

  return {
    errorCode: `${header}use strum_macros::{Display, EnumString};

use crate::util::position::Position;

${errorEnum}
#[derive(Debug, PartialEq)]
pub struct ErrorInfo {
    pub code: ErrorCode,
    pub additional_info: Option<String>,
}

#[derive(Debug, PartialEq)]
pub struct ErrorInfoWithPosition {
    pub error: ErrorInfo,
    pub position: Position,
}

/** Displays an error code and its optional context. */
impl std::fmt::Display for ErrorInfo {
    /** Writes the existing public error representation. */
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        let additional_info = match &self.additional_info {
            Some(info) => format!(": {}", info),
            None => "".to_string(),
        };
        write!(f, "{}{}", self.code, additional_info)
    }
}
`,
    warningCode: `${header}use strum_macros::Display;\n\n${warningEnum}`,
  };
}

if (import.meta.main) {
  const sources = generateDiagnosticSources();
  await writeFile(
    path.join(import.meta.dir, "../src/error_code.rs"),
    sources.errorCode,
  );
  await writeFile(
    path.join(import.meta.dir, "../src/warning_code.rs"),
    sources.warningCode,
  );
}
