// NOTE: Do not edit this file manually, it is generated by generate_diagnostic_codes.ts
use strum_macros::Display;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Display)]
pub enum WarningCode {
    #[strum(serialize = "DUPLICATE_EXTENSION")]
    /**
     * en: The same chord extension is specified more than once
     * ja: 同じコード拡張が複数回指定されています
     */
    DuplicateExtension,
}
